---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: $NAME
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
    volumes:
      - radarr-config:/config
      - /mnt/hgfs/media_shared/Films:/movies #optional
      - /mnt/hgfs/media_shared/Download:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
  radarr-config: