#v2
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: $NAME
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $CONFIG:/config
      - $CACHE:/cache
      - type: bind
        source: $MEDIA
        target: /media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  
