---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: $NAME
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
    volumes:
      - "${CONFIG_VOLUME}:/config"
      #- "${BOOKS_VOLUME}:/books" #optional
      - "${DOWNLOADS_VOLUME}:/downloads" #optional
    ports:
      - 8787:8787
    restart: unless-stopped
volumes:
  ${CONFIG_VOLUME}:
 # $BOOKS_VOLUME:
  ${DOWNLOADS_VOLUME}: