---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: $NAME
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
      - WEBUI_PORT=8090
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - /mnt/hgfs/media_shared:/downloads #optional
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
volumes:
  qbittorrent-config:
