---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: $NAME
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=$WEB_PORT
      - TORRENTING_PORT=Canada/Eastern
    volumes:
      - qbittorrent-config:/config
      - /mnt/hgfs/media_shared/books:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
volumes:
  qbittorrent-config:
