services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: $NAME
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
volumes:
  prowlarr-config: