---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: $NAME
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
    volumes:
      - config:/config
      - books:/books #optional
      - /mnt/hgfs/media_shared/books:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
volumes:
  config:
  books:
  downloads:
