services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: $NAME
    ports:
      - '${PORT}:8080'
    volumes:
      - /mnt/hgfs/services/stirling-pdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /mnt/hgfs/services/stirling-pdf/extraConfigs:/configs
      - /mnt/hgfs/services/stirling-pdf/customFiles:/customFiles/
      - /mnt/hgfs/services/stirling-pdf/logs:/logs/
      - /mnt/hgfs/services/stirling-pdf/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB