---
version: "2.1"
services:
  paperless-ng:
    image: lscr.io/linuxserver/paperless-ng:latest
    container_name: paperless-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
      - REDIS_URL= #optional
    volumes:
      - /mnt/hgfs/services/paperless-ng/config:/config
      - /mnt/hgfs/services/data:/data
    ports:
      - 8001:8001
    restart: unless-stopped
